### ISSUE TITLE
Not a function

### ISSUE THREAD

**Issue by jc-wood** [zhanghai/Untracker#11]
![Screenshot_20240103-095009.png](https://github.com/zhanghai/Untracker/assets/22546655/ed77e4ab-48ba-461e-917c-fadb4437bdac)

I wrote a filter for tiktok URLs. It was working for quite a while and then it just randomly broke. I haven't changed the script and the app hasn't been updated. Not sure what the issue is.

Scripts are as follows:

```
if ($.matches(url, '(www\\.)?tiktok\\.com')) {
    return $.followRedirect(url);
}
```

```
if ($.matches(url, '(www\\.)?tiktok\\.com')) {
    return $.setEncodedQuery(url, null);
}
```

**Comment by zhanghai** [comment]
I think your app has been updated where I removed the `followRedirect` function. You can check the updated built-in short link rule for how to use the new `$.fetch` which is more generic an I plan to maintain compatibility for.

**Comment by jc-wood** [comment]
That looks to have fixed it.
