### ISSUE TITLE
BV解析出了负数AV

### ISSUE THREAD

**Issue by leihao** [zhanghai/Untracker#19]
## Expected Behavior
https://m.bilibili.com/video/BV1b7421K7r9

## Actual Behavior
https://www.bilibili.com/video/av-497455601/

## Steps to Reproduce the Problem

1.略
1.
1.

## Specifications

- Version:1.0.3（4）
- Platform:

**Comment by zhanghai** [comment]
我尝试了多个 BV 转 AV 转换器都不支持这个 BV 号。你知道应该如何修改算法吗？

**Comment by leihao** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/misc/bvid_desc.md
试了一下这里提供的算法可以正常算出
相关的讨论:https://github.com/SocialSisterYi/bilibili-API-collect/issues/740

**Comment by zhanghai** [comment]
谢谢！
