### ISSUE TITLE
Doesn't recognise common redirects and other trash

### ISSUE THREAD

**Issue by HarriBuh** [zhanghai/Untracker#20]
![markup_1000004448.png](https://github.com/zhanghai/Untracker/assets/123186113/2ebd2fc6-9a09-46d4-87e3-17c27b1b1cca)

How it should have looked like:

![Screenshot_20240203-162043.png](https://github.com/zhanghai/Untracker/assets/123186113/775cdf54-0753-4f50-b5da-d912dec7b557)

**Comment by zhanghai** [comment]
This app can't help with every website and how they treat their links. You can create your custom rule for it though.
