### ISSUE TITLE
Support `163cn.tv` links

### ISSUE THREAD

**Issue by MkQtS** [zhanghai/Untracker#21]
Link: `http://163cn.tv/uf2FY2`

**Comment by zhanghai** [comment]
Do you happen to know how to clean up `music.163.com` URLs? Is it sufficient to only keep the `id` parameter, or are there anything else to keep as well?

**Comment by zhanghai** [comment]
Thanks! I decided to not touch the URL hash for now and only deal with the tracking parameters for `y.music.163.com` on mobile.
