### ISSUE TITLE
Can't figure out custom rule to remove "?" and on

### ISSUE THREAD

**Issue by KeronCyst** [zhanghai/Untracker#31]
## Expected Behavior
Remove everything including and after "?" for https://www.msn.com/en-us/money/personalfinance/2-banks-are-offering-2-500-for-opening-an-account-right-now-and-12-more-biggest-cash-signup-bonuses-for-april-2024-up-to-5-000/ar-BB1lnUF9?ocid=msedgntp&pc=U531&cvid=b90e17410c9142bd9e2f4da19e5c011f&ei=7

## Actual Behavior
Link unchanged

## Steps to Reproduce the Problem

1. Share https://www.msn.com/en-us/money/personalfinance/2-banks-are-offering-2-500-for-opening-an-account-right-now-and-12-more-biggest-cash-signup-bonuses-for-april-2024-up-to-5-000/ar-BB1lnUF9?ocid=msedgntp&pc=U531&cvid=b90e17410c9142bd9e2f4da19e5c011f&ei=7

## Specifications

- Version: 1.0.4 (5)
- Platform: Android 12 on Samsung One UI 4.0

**Comment by zhanghai** [comment]
Try `return $.removeQueryParameters(url);`
