### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by VolodymyrPrykhodkov** [zhanghai/Untracker#5]
## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by VolodymyrPrykhodkov** [comment]
And where to take scripts to the applications?

**Comment by zhanghai** [comment]
Do you have an example of the Facebook URL you want to transform? Becuase I haven't used Facebook for a long time.

> And where to take scripts to the applications?

If you mean adding a custom script, you can press the "+" icon on the top-right of the "Rules" tab.

**Comment by shenzero123** [comment]
> ## Expected Behavior
> ## Actual Behavior
> ## Steps to Reproduce the Problem
> 
> ## Specifications
> * Version:
> * Platform:

Copy built-in script of instagram then into custom rule, paste code of instagram built-in to script custom then change name instagram to facebook and done.
Now, you enter fb, you just share 1 post through untrack apps and it will remove tracking for you. Good luck

**Comment by shenzero123** [comment]
![Screenshot_2024-04-24-23-03-02-08_5566d37acfd9a5fc11e6b5743b805a56](https://github.com/zhanghai/Untracker/assets/155952007/62ebabce-87df-47f6-a6f7-25c0ffcb7fac)
This is tracking from facebook and untrack removed it
It always is <?mibextid=> or something like that

**Comment by VolodymyrPrykhodkov** [comment]
Thank you very much. Sorry for not answering. I don't have time for this
anymore. I'm busy surviving (there's a war at home).
   I wish you a lot of useful experience from good and active colleagues.

чт, 14 дек. 2023 г., 16:57 Hai Zhang ***@***.***>:
