### ISSUE TITLE
Amazon

### ISSUE THREAD

**Issue by linuzzx** [zhanghai/Untracker#6]
## Expected Behavior
should strip a lot of trackers and unnessesary url infos

## Actual Behavior
Does nothin

## Steps to Reproduce the Problem

1. Browse a bit around amazon
1. Share a product link to app
1. see °-°

## Specifications

- Version: newest rn
- Platform: aosp android

**Comment by zhanghai** [comment]
Works fine for me - there's a built-in rule for Amazon that drops all URL query parameters, and I can get links like https://www.amazon.com/dp/QWERTY when I share from Amazon to Untracker.

Do you have more details on which URL isn't working?

**Comment by linuzzx** [comment]
https://www.amazon.de/Die-Einladung-Psychothriller-Sebastian-Fitzek/dp/3426281589/ref=zg_m_bs_c_books_sccl_2/260-4844017-9717546?pd_rd_w=WKsTR&content-id=amzn1.sym.22f8be38-f3b8-454d-b680-116ba0143174&pf_rd_p=22f8be38-f3b8-454d-b680-116ba0143174&pf_rd_r=FY1N5B0PQEDZY6694YD9&pd_rd_wg=ZNlh6&pd_rd_r=e30e8b97-db91-4a6a-aecd-3a10b5b77c73&pd_rd_i=3426281589&psc=1

For example

**Comment by zhanghai** [comment]
Oh, that's because the rule only applied to the `amazon.com` domain... I'll add more domains.

**Comment by linuzzx** [comment]
Great thanks, have a good day
