### ISSUE TITLE
Buttons blocked by system navigation bar

### ISSUE THREAD

**Issue by frabarz** [zhanghai/Untracker#7]
## Expected Behavior
The buttons should be above the system navigation bar, free to be pressed.

## Actual Behavior
The buttons get rendered behind the system navigation bar and are blocked by the nav buttons.

## Steps to Reproduce the Problem

1. Change the navigation bar mode in the system settings to '3 button mode' (Back, Home, Recent apps buttons)
1. Try to share a link to Untracker
1. The Copy and Share buttons get rendered behind the navigation bar.

## Specifications

- Version: 1.0.0, installed from F-Droid
- Platform: Android 10, in a OnePlus 6

https://github.com/zhanghai/Untracker/assets/11713191/59ce0b7c-fe38-41e8-9204-7dbb4cbb2f78

**Comment by zhanghai** [comment]
(Planning to release a new version with this fix next weekend.)

**Comment by zhanghai** [comment]
Released a new version with some extra improvements today and should be on Play now.
