### ISSUE TITLE
Customisable default option

### ISSUE THREAD

**Issue by VishnuSanal** [zhanghai/Untracker#9]
Option to default to share/copy the cleaned link without having to do an extra click on the UI.

PS: if this seems viable, I'd like to work on this issue :)

**Comment by zhanghai** [comment]
The links are not expected to be always transformed immediately, for example expanding the short link may take seconds, so it can't be a seamless experience. Whereas if we show the UI during the time it's processing then the UI dismissing itself is also a bit strange given that the user has already seen the UI which can provide alternatives that's just one click away. So unfortunately I don't think this can work well (also the reason I didn't implement it myself.)

**Comment by VishnuSanal** [comment]
> The links are not expected to be always transformed immediately, for example expanding the short link may take seconds, so it can't be a seamless experience. Whereas if we show the UI during the time it's processing then the UI dismissing itself is also a bit strange given that the user has already seen the UI which can provide alternatives that's just one click away. So unfortunately I don't think this can work well (also the reason I didn't implement it myself.)

alright, thanks for the detailed explanation.
